// Generated by scripts/sync_clients.py — do not edit by hand.
// Axiom policy hooks for OpenCode (v1 line, see docs/OPENCODE_COMPAT.md).
//
// Module shape verified against @opencode-ai/plugin 1.18.31
// (PluginModule: the file exports `server`, a Plugin function receiving
// {project, client, $, directory, worktree} and returning a Hooks map).
// Live-load smoke test: `axiom oc run --dry-run` only resolves config;
// a keyed headless run is required to observe these hooks (Phase 2c CI
// asserts at least that a headless run shows no plugin-load error).
//
// The guard below is deliberately narrow: it only ever *blocks* reads of
// obvious secrets files, and it only ever *observes* otherwise. Anything
// unexpected falls through (fail-open for completion, fail-closed only
// for the secrets read).

export const server = async (input: {
  directory: string;
  project?: unknown;
  client?: unknown;
  $?: unknown;
  worktree?: unknown;
}) => {
  const directory: string = input.directory ?? process.cwd();
  const logTarget: string | undefined = process.env.AXIOM_TOOL_LOG;
  const secrets = /(^|[\\/])\.env(\..*)?$/;

  const mentionsSecretsFile = (value: unknown): string | null => {
    if (typeof value === "string" && secrets.test(value)) return value;
    if (Array.isArray(value)) {
      for (const item of value) {
        const hit = mentionsSecretsFile(item);
        if (hit) return hit;
      }
    } else if (value !== null && typeof value === "object") {
      for (const item of Object.values(value)) {
        const hit = mentionsSecretsFile(item);
        if (hit) return hit;
      }
    }
    return null;
  };

  return {
    "tool.execute.before": async (_in: unknown, out: { args?: unknown }) => {
      // Policy gate (AUDIT §3): never let the session read secrets files.
      // Throwing aborts the tool call; any other shape passes through.
      const hit = mentionsSecretsFile(out?.args);
      if (hit) throw new Error(`axiom-policy: refusing to read secrets file: ${hit}`);
    },
    "tool.execute.after": async (
      input: { tool: string; sessionID: string },
      _output: unknown,
    ) => {
      // Redacted tool-call log: tool name + session only — never args or
      // output (both may carry secrets). Opt-in via AXIOM_TOOL_LOG=<path>.
      if (!logTarget) return;
      const line = JSON.stringify({
        ts: new Date().toISOString(),
        tool: input.tool,
        session: input.sessionID,
      });
      await Bun.write(logTarget, line + "\n").catch(() => {});
    },
    "experimental.session.compacting": async (
      _input: unknown,
      output: { context: string[] },
    ) => {
      // Keep the Axiom contract alive across compaction (traceability).
      output.context.push(
        "Axiom contract reminder: Discover → Plan → select context → Change → " +
          "Verify → Evidence. Preserve scope; record human approval before " +
          "push/release/destructive or safety/security-critical changes. " +
          "Never claim certification or compliance from a heuristic check.",
      );
    },
  };
};
