"""Read-only auditor for Phase 1 of embedded-skills-deep-update.

Scores each skill in skills/ across 10 categories and emits:
- artifacts/gap-analysis/skills_gap_analysis.md
- artifacts/gap-analysis/skills_gap_analysis.json

Read-only except for the artifacts output directory.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
REGISTRY = REPO_ROOT / "registries" / "skills.json"
OUT_DIR = REPO_ROOT / "artifacts" / "gap-analysis"

CATEGORIES = [
    "readme",
    "requirements",
    "architecture",
    "src",
    "headers",
    "test",
    "build",
    "compliance",
    "validation",
    "docs",
]

# Current skill layout is SKILL.md + manifest.yaml; richer layouts score higher.
EXPECTED_SECTIONS = ["objectives", "prereqs", "outcomes", "time", "resources"]


def load_registry_ids() -> list[str]:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    return [s["id"] for s in data.get("skills", [])]


def score_skill(skill_dir: Path) -> dict:
    skill_md = skill_dir / "SKILL.md"
    manifest = skill_dir / "manifest.yaml"
    text = skill_md.read_text(encoding="utf-8").lower() if skill_md.exists() else ""
    gaps: list[str] = []
    scores: dict[str, int] = {}

    # readme: SKILL.md depth (current files are stubs ~5 lines)
    if not skill_md.exists():
        scores["readme"] = 0
        gaps.append("missing SKILL.md")
    else:
        hits = sum(1 for s in EXPECTED_SECTIONS if s in text)
        line_count = len(text.splitlines())
        if line_count <= 10:
            scores["readme"] = 10
            gaps.append("SKILL.md is stub (<10 lines), missing objectives/outcomes/time-estimate")
        else:
            scores["readme"] = min(100, 20 + hits * 16 + min(20, line_count // 10))

    # manifest presence
    if not manifest.exists():
        gaps.append("missing manifest.yaml")

    # Remaining categories: current flat skills carry content in SKILL.md only,
    # so sub-artifacts (requirements/, architecture/, src/, test/, ...) are absent.
    for cat in CATEGORIES[1:]:
        subdir = skill_dir / cat
        if subdir.exists():
            scores[cat] = 60
        else:
            scores[cat] = 5 if len(text.splitlines()) > 10 else 0
            gaps.append(f"missing {cat}/ sub-artifact or equivalent section")

    avg = sum(scores.values()) / len(scores) if scores else 0
    if avg < 30:
        priority = "high"
    elif avg < 70:
        priority = "medium"
    else:
        priority = "low"
    effort = round(max(1.0, (100 - avg) / 20), 1)
    return {"scores": scores, "gaps": gaps, "priority": priority, "effort": effort}


def main() -> int:
    ids = load_registry_ids()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    reports = []
    for skill_id in sorted(ids):
        result = score_skill(SKILLS_DIR / skill_id)
        reports.append(
            {
                "skill_id": skill_id,
                "categories": result["scores"],
                "gaps": result["gaps"],
                "priority": result["priority"],
                "effort_person_days": result["effort"],
            }
        )
    json_path = OUT_DIR / "skills_gap_analysis.json"
    json_path.write_text(json.dumps(reports, indent=2), encoding="utf-8")

    lines = [
        "# Skills Gap Analysis",
        "",
        "Generated by `scripts/audit_skills.py` (Phase 1, read-only audit).",
        f"Skills audited: {len(reports)}",
        "",
        "| Skill | Avg % | Priority | Effort (pd) | Top gaps |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in reports:
        avg = sum(r["categories"].values()) / len(r["categories"])
        top = "; ".join(r["gaps"][:3])
        lines.append(f"| {r['skill_id']} | {avg:.0f} | {r['priority']} | {r['effort_person_days']} | {top} |")
    lines += [
        "",
        "## Priority recommendations",
        "",
        "- high: template-first skills (mcu, rtos, autosar, safety, embedded-linux, edge-ai, robotics)",
        "- medium: engineering process skills (requirements, architecture, test, traceability, evidence)",
        "- low: none until template lands; re-score after Phase 3",
        "",
        "## Notes",
        "",
        "- Current skills are flat `SKILL.md + manifest.yaml` stubs; domain depth lives in `domains/` overlays.",
        "- Phase 3 must update skills in place, one branch per skill, with ADRs and standards citations.",
    ]
    (OUT_DIR / "skills_gap_analysis.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Audited {len(reports)} skills -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
