#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Single source of truth -> per-client generated files.

skills/ and agents/ are the only hand-edited sources. Everything below is
derived and must not be edited by hand:

  .opencode/agents/<id>.md          OpenCode subagent (provisional format)
  .opencode/skills/<id>/SKILL.md    OpenCode skill copy (provisional format)
  opencode.json                     instructions + mcp (permission/agent preserved)
  .claude/agents/<id>.md            Claude Code subagent
  .claude/skills/<id>/SKILL.md      Claude Code skill copy
  .claude-plugin/plugin.json        Claude plugin manifest
  .mcp.json                         MCP server entry (Codex/Cursor/VS Code)
  .github/copilot-instructions.md   Copilot repository-wide instructions
  GEMINI.md                         Gemini pointer + entry points

Client-specific formats are provisional until verified against live docs in
Phase 2 (docs/OPENCODE_COMPAT.md). Content always comes from source.

Usage:
    python scripts/sync_clients.py           # regenerate in place
    python scripts/sync_clients.py --check    # CI: exit 1 if stale
    python scripts/sync_clients.py --root DIR # generate against another root
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import yaml

STAMP_MD = "<!-- Generated by scripts/sync_clients.py — do not edit by hand. Source: skills/ agents/. -->\n"
STAMP_JSON = "Generated by scripts/sync_clients.py — do not edit by hand. Source: skills/ agents/."
MCP_SERVER = {
    "command": "python",
    "args": ["-m", "axiom_cli", "mcp"],
    "description": "AxiomEmbedded skills, plans, context, impact, and workflow tools",
}
# OpenCode v1 validates `mcp.*` strictly: `{type: "local", command: [...],
# enabled: ...}` (argv array, no {command, args} split). Verified against
# `opencode mcp list` (config validation runs without an API key).
OPENCODE_MCP_SERVER = {
    "type": "local",
    "command": ["python", "-m", "axiom_cli", "mcp"],
    "enabled": True,
}
INSTRUCTIONS = [
    "AGENTS.md",
    "CONTRIBUTING.md",
    "docs/agents/working-agreement.md",
    "docs/architecture/context-policy.md",
]


def split_frontmatter(text: str) -> tuple[dict, str]:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return yaml.safe_load(text[3:end]) or {}, text[end + 4 :].lstrip("\n")
    return {}, text


def load_skills(root: pathlib.Path) -> list[dict]:
    out = []
    for path in sorted((root / "skills").iterdir()):
        skill_md = path / "SKILL.md"
        if not path.is_dir() or not skill_md.exists():
            continue
        front, _body = split_frontmatter(skill_md.read_text(encoding="utf-8"))
        manifest_path = path / "manifest.yaml"
        manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
        out.append({
            "id": front.get("name", manifest.get("id", path.name)),
            "description": front.get("description", ""),
            "version": str(front.get("version", manifest.get("version", "0.0.0"))),
            "body": skill_md.read_text(encoding="utf-8"),
        })
    return out


def load_agents(root: pathlib.Path) -> list[dict]:
    out = []
    for path in sorted((root / "agents").iterdir()):
        agent_md = path / "AGENT.md"
        manifest_path = path / "manifest.json"
        if not path.is_dir() or not agent_md.exists() or not manifest_path.exists():
            continue
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        out.append({
            "id": manifest.get("id", path.name),
            "description": manifest.get("purpose", ""),
            "version": manifest.get("version", "0.0.0"),
            "manifest": manifest,
            "body": agent_md.read_text(encoding="utf-8"),
        })
    return out


def oc_permission(manifest: dict) -> dict:
    """OpenCode `permission:` allowlist derived from an agent manifest.

    Least privilege from declared data only: `edit` follows
    `permissions.filesystem`; every shell command asks except `git push`,
    which is denied outright (no manifest grants `git_push: true`).
    Bash globs list `*` first — OpenCode evaluates last-match-wins.
    """
    filesystem = (manifest.get("permissions", {}) or {}).get("filesystem", "read")
    return {
        "edit": "allow" if filesystem == "read-write" else "deny",
        "bash": {"*": "ask", "git push *": "deny"},
    }


def agent_file(agent: dict, *, for_opencode: bool) -> str:
    front = {"name": agent["id"], "description": agent["description"]}
    if for_opencode:
        # OpenCode-native subagents: `mode: subagent` keeps the primary
        # session clean; `permission:` is the v1 allowlist mechanism
        # (legacy `tools:` is deprecated — never generated).
        front["mode"] = "subagent"
        front["permission"] = oc_permission(agent["manifest"])
    return STAMP_MD + "---\n" + yaml.safe_dump(front, sort_keys=False) + "---\n\n" + agent["body"]


def skill_copy(skill_body: str) -> str:
    return STAMP_MD + skill_body


def copilot_instructions(skills: list[dict], agents: list[dict]) -> str:
    skill_list = "\n".join(f"- `{s['id']}` — {s['description']}" for s in skills)
    agent_list = "\n".join(f"- `{a['id']}` — {a['description']}" for a in agents)
    return (
        STAMP_MD
        + "# AxiomEmbedded — Copilot instructions\n\n"
        + "Read `AGENTS.md` first (repository contract), then task-specific skills.\n"
        + "Prefer the artifact graph over whole-repo reads. Discover → plan →\n"
        + "select context → change → verify → evidence.\n\n"
        + "## MCP tools (via the `axiom-embedded` MCP server)\n\n"
        + "- `engage(domain, platform)` — skill slice for the project\n"
        + "- `run_plan(request, domain, platform)` — plan-then-execute plan\n"
        + "- `read_skill(skill_id)` / `list_skills` / `list_profiles` — discovery\n"
        + "- `context_select`, `impact`, `workflow_plan`, `route` — analysis\n\n"
        + "## Approval gates (configs/project.yaml)\n\n"
        + "Surface the plan first; never execute pushes, releases, destructive\n"
        + "commands, or safety/security-critical changes without recorded human\n"
        + "approval. Never claim certification or compliance from a heuristic check.\n\n"
        + f"## Skills ({len(skills)})\n\n{skill_list}\n\n"
        + f"## Specialist agents ({len(agents)})\n\n{agent_list}\n"
    )


def gemini_md(version: str, skills: list[dict]) -> str:
    return (
        STAMP_MD
        + "# AxiomEmbedded\n\n"
        + "Use `AGENTS.md` as the repository contract. Prefer indexed/context-selected\n"
        + "reads over repository-wide loading and preserve the project\n"
        + "evidence/traceability model.\n\n"
        + "## Entry points\n\n"
        + "- MCP server: `python -m axiom_cli mcp` (tools: engage, run_plan,\n"
        + "  read_skill, list_skills, list_profiles, context_select, impact, ...)\n"
        + "- CLI: `axiom engage|run|analyze|graph|context|impact|status|fix|feature`\n"
        + "  (or `python -m axiom_cli ...` without install)\n"
        + "- REST/A2A: `axiom serve --port 8931`\n\n"
        + f"Ships {len(skills)} skills (see `registries/skills.json`), "
        + f"axiom-embedded {version}.\n"
    )


def opencode_json(existing: dict) -> dict:
    merged = dict(existing)
    merged["$schema"] = "https://opencode.ai/config.json"
    merged["//"] = STAMP_JSON
    merged["instructions"] = list(INSTRUCTIONS)
    mcp = dict(merged.get("mcp", {}))
    mcp["axiom-embedded"] = dict(OPENCODE_MCP_SERVER)
    merged["mcp"] = mcp
    return merged


# `/axiom-*` slash commands (OpenCode only). Each command is a thin wrapper
# over the axiom CLI via shell injection, so behaviour stays defined once.
# `subtask: true` is reserved for research-style commands that must not
# pollute the primary context (verified in docs/OPENCODE_COMPAT.md).
COMMANDS = [
    {
        "id": "axiom-engage",
        "description": "Select the Axiom skill slice for a domain/platform",
        "body": ("Engage the Axiom skill slice and report what to load, in order.\n\n"
                 "```\n!`axiom engage $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-engage [--domain NAME] [--platform NAME]`."),
    },
    {
        "id": "axiom-plan",
        "description": "Emit an Axiom plan-then-execute plan for a request",
        "body": ("Emit the Axiom plan-then-execute plan below and surface it for approval. "
                 "Do not implement yet.\n\n"
                 "```\n!`axiom run $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-plan <request> [--domain NAME] [--platform NAME]`."),
    },
    {
        "id": "axiom-status",
        "description": "Show the Axiom project health dashboard",
        "body": ("```\n!`axiom status`\n```\n\nAct on the single recommended next action."),
    },
    {
        "id": "axiom-fix",
        "description": "Emit the Axiom 10-step fix-defect plan for an issue",
        "body": ("Emit the fix-defect plan and surface it for approval before changing code.\n\n"
                 "```\n!`axiom fix $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-fix <issue-id> [--domain NAME] [--platform NAME]`."),
    },
    {
        "id": "axiom-feature",
        "description": "Emit the Axiom 9-step add-feature plan for a feature",
        "body": ("Emit the add-feature plan and surface it for approval before changing code.\n\n"
                 "```\n!`axiom feature $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-feature <feature-id> [--domain NAME] [--platform NAME]`."),
    },
    {
        "id": "axiom-impact",
        "description": "Assess Axiom change impact for a project profile",
        "body": ("```\n!`axiom impact $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-impact <profile.yaml>`. Summarise entry mode and next phase."),
    },
    {
        "id": "axiom-context",
        "description": "Select bounded Axiom context for artifact roots",
        "body": ("```\n!`axiom context select $ARGUMENTS`\n```\n\n"
                 "Usage: `/axiom-context --root <artifact> [--root ...]`. Read only the selected files."),
    },
    {
        "id": "axiom-research",
        "description": "Research-only investigation (no file changes)",
        "agent": "explore",
        "subtask": True,
        "body": ("Research only: investigate and report. Do not modify, create, or delete "
                 "any files.\n\nQuestion: $ARGUMENTS\n\n"
                 "End with a short findings summary plus source paths."),
    },
]


def command_file(command: dict) -> str:
    front: dict = {"description": command["description"]}
    if command.get("agent"):
        front["agent"] = command["agent"]
    if command.get("subtask"):
        front["subtask"] = True
    return STAMP_MD + "---\n" + yaml.safe_dump(front, sort_keys=False) + "---\n\n" + command["body"] + "\n"


PLUGIN_TS = """// Generated by scripts/sync_clients.py — do not edit by hand.
// Axiom policy hooks for OpenCode (v1 line, see docs/OPENCODE_COMPAT.md).
//
// Module shape verified against @opencode-ai/plugin 1.18.31
// (PluginModule: the file exports `server`, a Plugin function receiving
// {project, client, $, directory, worktree} and returning a Hooks map).
// Live-load smoke test: `axiom oc run --dry-run` only resolves config;
// a keyed headless run is required to observe these hooks (Phase 2c CI
// asserts at least that a headless run shows no plugin-load error).
//
// The guard below is deliberately narrow: it only ever *blocks* reads of
// obvious secrets files, and it only ever *observes* otherwise. Anything
// unexpected falls through (fail-open for completion, fail-closed only
// for the secrets read).

export const server = async (input: {
  directory: string;
  project?: unknown;
  client?: unknown;
  $?: unknown;
  worktree?: unknown;
}) => {
  const directory: string = input.directory ?? process.cwd();
  const logTarget: string | undefined = process.env.AXIOM_TOOL_LOG;
  const secrets = /(^|[\\\\/])\\.env(\\..*)?$/;

  const mentionsSecretsFile = (value: unknown): string | null => {
    if (typeof value === "string" && secrets.test(value)) return value;
    if (Array.isArray(value)) {
      for (const item of value) {
        const hit = mentionsSecretsFile(item);
        if (hit) return hit;
      }
    } else if (value !== null && typeof value === "object") {
      for (const item of Object.values(value)) {
        const hit = mentionsSecretsFile(item);
        if (hit) return hit;
      }
    }
    return null;
  };

  return {
    "tool.execute.before": async (_in: unknown, out: { args?: unknown }) => {
      // Policy gate (AUDIT §3): never let the session read secrets files.
      // Throwing aborts the tool call; any other shape passes through.
      const hit = mentionsSecretsFile(out?.args);
      if (hit) throw new Error(`axiom-policy: refusing to read secrets file: ${hit}`);
    },
    "tool.execute.after": async (
      input: { tool: string; sessionID: string },
      _output: unknown,
    ) => {
      // Redacted tool-call log: tool name + session only — never args or
      // output (both may carry secrets). Opt-in via AXIOM_TOOL_LOG=<path>.
      if (!logTarget) return;
      const line = JSON.stringify({
        ts: new Date().toISOString(),
        tool: input.tool,
        session: input.sessionID,
      });
      await Bun.write(logTarget, line + "\\n").catch(() => {});
    },
    "experimental.session.compacting": async (
      _input: unknown,
      output: { context: string[] },
    ) => {
      // Keep the Axiom contract alive across compaction (traceability).
      output.context.push(
        "Axiom contract reminder: Discover → Plan → select context → Change → " +
          "Verify → Evidence. Preserve scope; record human approval before " +
          "push/release/destructive or safety/security-critical changes. " +
          "Never claim certification or compliance from a heuristic check.",
      );
    },
  };
};
"""


def claude_plugin_json(version: str) -> dict:
    return {
        "//": STAMP_JSON,
        "name": "axiom-embedded",
        "version": version,
        "description": "Domain-neutral embedded engineering skills, agents, and MCP tools.",
    }


def mcp_json() -> dict:
    return {"//": STAMP_JSON, "mcpServers": {"axiom-embedded": dict(MCP_SERVER)}}


def build_all(root: pathlib.Path) -> dict[str, str]:
    """Return {relative_posix_path: file_text} for every generated file."""
    skills = load_skills(root)
    agents = load_agents(root)
    version = (root / "VERSION").read_text(encoding="utf-8").strip()
    files: dict[str, str] = {}
    for a in agents:
        files[f".opencode/agents/{a['id']}.md"] = agent_file(a, for_opencode=True)
        files[f".claude/agents/{a['id']}.md"] = agent_file(a, for_opencode=False)
    for s in skills:
        content = skill_copy(s["body"])
        files[f".opencode/skills/{s['id']}/SKILL.md"] = content
        files[f".claude/skills/{s['id']}/SKILL.md"] = content
    for c in COMMANDS:
        files[f".opencode/commands/{c['id']}.md"] = command_file(c)
    files[".opencode/plugins/axiom-policy.ts"] = PLUGIN_TS
    existing_path = root / "opencode.json"
    existing = json.loads(existing_path.read_text(encoding="utf-8")) if existing_path.exists() else {}
    files["opencode.json"] = json.dumps(opencode_json(existing), indent=2) + "\n"
    files[".claude-plugin/plugin.json"] = json.dumps(claude_plugin_json(version), indent=2) + "\n"
    files[".mcp.json"] = json.dumps(mcp_json(), indent=2) + "\n"
    files[".github/copilot-instructions.md"] = copilot_instructions(skills, agents)
    files["GEMINI.md"] = gemini_md(version, skills)
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate per-client files from skills/ and agents/.")
    ap.add_argument("--check", action="store_true", help="Exit 1 if any generated file is stale.")
    ap.add_argument("--root", default=str(pathlib.Path(__file__).resolve().parents[1]))
    args = ap.parse_args()
    root = pathlib.Path(args.root)
    files = build_all(root)
    stale: list[str] = []
    for rel, text in files.items():
        path = root / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(rel)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print("Stale generated files (run python scripts/sync_clients.py):")
        for rel in stale:
            print(f"  {rel}")
        return 1
    if not args.check:
        print(f"Synced {len(files)} files from {len(load_skills(root))} skills, {len(load_agents(root))} agents.")
    else:
        print(f"All {len(files)} generated files are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
